#!/usr/bin/env sh

echo '
      🏗️👷 Styling your project before committing 👷‍♂️🏗️
      please be patient, this may take a while...
      ';

bun lint --fix ||
(
    echo '
          🔨❌ You have a problem in your code. Check linter 🔨❌
          Run npm lint, fix errors, add changes and try commit again.
          ';
    false;
)

echo '
      🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻
     '
