#!/usr/bin/env sh

echo '
      🏗️👷 Runing your tests before pushing 👷‍♂️🏗️
      please be patient, this may take a while...
      ';

bun jest || 
(
  echo '
         🔨❌ You have a problem in your code. Check your tests 🔨❌
         Run npm test to know which tests are failing
       ';
  false;
)

echo '
      🎉 Tests done: Pushing changes now.... ✨🚀🏄‍♂️🍻
     '
